#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
################################################################################

SB_CONFIG_BOOTLOADER_MCUBOOT=y
# Disable Partition Manager when using MCUboot RAM loading mode.
SB_CONFIG_PARTITION_MANAGER=n
SB_CONFIG_MCUBOOT_MODE_RAM_LOAD=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_PURE=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/images/mcuboot/mcuboot_private.pem"

# Temporarily use the SW crypto in the MCUboot bootloader and the verification key storage
# without KMU.
SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=n

# KMU is currently not working. Possibly it's because of the following warning:
#
# [74/78] Linking C executable zephyr/zephyr_pre0.elf
# /home/alst/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: warning: orphan section `.nrf_kmu_reserved_push_area' from `/tmp/cc6COg65.ltrans2.ltrans.o' being placed in section `.nrf_kmu_reserved_push_area'
# [78/78] Linking C executable zephyr/zephyr.elf
# /home/alst/zephyr-sdk-0.16.8/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: warning: orphan section `.nrf_kmu_reserved_push_area' from `/tmp/ccJMpD4R.ltrans2.ltrans.o' being placed in section `.nrf_kmu_reserved_push_area'
#
# I suspect it's because KMU has some assumptions on RAM start address.
# SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=y
# SB_CONFIG_MCUBOOT_GENERATE_DEFAULT_KMU_KEYFILE=y
