#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
################################################################################

SB_CONFIG_BOOTLOADER_MCUBOOT=y
# Disable Partition Manager when using MCUboot RAM loading mode.
SB_CONFIG_PARTITION_MANAGER=n
SB_CONFIG_MCUBOOT_MODE_RAM_LOAD=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_PURE=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APPLICATION_CONFIG_DIR}/images/mcuboot/mcuboot_private.pem"

# Use the SW crypto in the MCUboot bootloader and the verification key storage without KMU.
SB_CONFIG_MCUBOOT_SIGNATURE_USING_KMU=n

# KMU is currently not working. It's because of the following assumption in
#zephyr/soc/nordic/nrf54l/CMakeLists.txt: "The KMU has a static destination address, we chose
# this address to be 0x20000000, which is the first address in the SRAM.". In the RAM load mode,
# the linker script places the code at the beginning of SRAM and RAM is put after the code.
# It doesn't seem to be easy to change this linker script behavior.
